### PR TITLE
feat: Problem 10 solution -- NO PEEKING!

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@gabrilend Don't peek lol

**Comment by ghost** [comment]
Ninja push problem 3 solution in bash. Bad idea. Bash just can't handle these arrays.

**Comment by gabrilend** [comment]
HOW AM I SUPPOSED TO MERGE THIS IF I CAN'T PEAK

**Comment by ghost** [comment]
Oops. Deleted my repo lol

**Comment by gabrilend** [comment]
:O :O :O

does that mean all your work is gone? I'm still not peeking!

**Pull request closed without merging**
